### ISSUE TITLE
Is it possible to assign a jpg image as the thumbnail for a video?

### ISSUE THREAD

**Issue by j3dj3d** [jwplayer/wordpress-plugin#36]
Hi is there some way in the Wordpress plugin to associate a particular .jpg to be the image that comes up first while the video is starting up or to represent the video in a playlist? Used to be able to do this with the previous html website versions of jw player.

**Comment by rmnl** [comment]
@j3dj3d The preferred method of doing this is through the [JW Player Dashboard](https://dashboard.jwplayer.com/).

**Comment by rob** [comment]
@rmnl I have uploaded custom images > 2000px before and it doesn't matter. If you use JW's hosted player and try to embed content you've uploaded via JW, the thumbnail generated by JW for the embed is always outputted at 720px wide no matter what. There's nothing to change in the URL because it's entirely generated by JW:

http://content.jwplatform.com/previews/kztHiJa3-8Up0Ro0n

Also, using this plugin, it seems the image (with the -720) is also included in an inline CSS style:

![screen shot 2016-10-24 at 11 03 57 am](https://cloud.githubusercontent.com/assets/503/19651119/a5171b7c-99d9-11e6-9d8a-d1abd4f2f7ea.png)

We have a JW player embed on this page, and the custom thumbnail (which was well over 2000px) shows at 720px wide and looks blurry on our large retina monitors:

[http://cobblestonecorridor.org/](http://cobblestonecorridor.org/)
